### PR TITLE
Improve regex 

### PR DESCRIPTION
**Pull request by Sebastian-Nielsen**
Improve regex to treat contracted words as one and treat words containing a hyphen as one word.

Eg
This contracted word is treated as two distinct ones: `it's` -> `["it", "s"]`
It would be better if it was treated as one word.

### CODE REVIEW

**Comment by Sebastian-Nielsen** [comment]
Is there a reason for the use of `RegexpTokenizer`?

I find: 
`    words = re.findall(r"[a-zA-Z_'-]+", news)`

better suiting than:
```
tokenizer = RegexpTokenizer(r"[a-zA-Z_'-]+")
words = tokenizer.tokenize(news)
```

Not that it is important, I am just curious.

**Comment by DavidIsrawi** [comment]
Agreed with the change in the regex, great point. 

For the regex library used, either it is `RegexpTokenizer` or re, it still needs to be imported, so as NLTK is used for everyone else, I found the use of this library for regex better for consistency. The tradeoff would be the light space that `re` would take instead of `RegexpTokenizer`, but make sure that your commit includes importing the library!

**Comment by FreezePhoenix** [comment]
I think that this is a good addition. I know Repo Owner gets final say, but congrats @Sebastian-Nielsen For the accuracy and keen eye to find this.

As for you, @DavidIsrawi you are one of the best Repo Owners I have seen in a while.

**Comment by Sebastian-Nielsen** [comment]
Good point regarding the consistency.

**Comment by DavidIsrawi** [comment]
Agreed with @TheOneWhoMade, if you change the imports to the project then it seems like a good addition

**Comment by FreezePhoenix** [comment]
@DavidIsrawi  can I use this in an AI project of mine? If so, do you have a lighter version? I want him to be able to interact with all chat lengths, not only those below 100 characters.

**Comment by Sebastian-Nielsen** [comment]
@DavidIsrawi I re-commited the pull request to use the `RegexpTokenizer` with my updated regex, as I think you are right regarding the code consistency. There should be no need to change any imports.

**Comment by DavidIsrawi** [comment]
Feel free to follow the code, this is a pretty light version but would suggest you rewrite it in order to make it lighter or more catered to your project. Use this article for help:
> https://dev.to/davidisrawi/build-a-quick-summarizer-with-python-and-nltk

If you have any questions regarding the code, let me know @TheOneWhoMade

**Comment by FreezePhoenix** [comment]
@DavidIsrawi if you approve of the change, please merge the pull request.
Also, is this a standalone? As in, 0 dependencies? I need this to be able to be embedded in a webpage.

**Comment by DavidIsrawi** [comment]
NLTK should be your only issue, however, you can rebuild it using only regex, TFIDF, and built-in functions. The main challenge would be the sentence tokenizer (not sure if the Stemmer could be implemented) but it can be all done with `re` and `blob` (one option for TFIDF implementation) as the only dependencies. It'll become way lighter @TheOneWhoMade

**Pull request merged**
